name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile C Program
      run: gcc src/main.c -o hello_world

    - name: Execute the program
      run: ./hello_world

    - name: Check output
      run: |
        output=$(./hello_world)
        if [ "$output" != "Ola mundo!" ]; then
          echo "Test failed: Output was '$output' instead of 'Ola mundo!'"
          exit 1
        fi
