name: Run Tests and Notify Discord

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile C Program
        run: gcc src/main.c -o hello_world

      - name: Enviar alerta para o Discord
        if: always() # Sempre executa essa etapa, passando ou falhando
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            STATUS="[OK] Testes passaram com sucesso!"
            COLOR="00ff88"
          else
            STATUS="[X] Testes falharam!"
            COLOR="ff0049"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"embeds\":[{\"title\":\"Status do CI/CD\",\"description\":\"${STATUS}\",\"color\":${COLOR}}]}" \
            $DISCORD_WEBHOOK